-- ============================================================================
-- Meatapivot Database Schema v2.0
-- PostgreSQL 15+ with pgcrypto & uuid-ossp extensions
-- ============================================================================
-- Run: psql -U postgres -d meatapivot -f schema.sql
-- ============================================================================

-- Enable extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================================
-- 1. Tenant & User (Existing baseline, preserved)
-- ============================================================================

CREATE TABLE IF NOT EXISTS tenants (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    description TEXT,
    config JSONB DEFAULT '{}',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    hashed_password VARCHAR(255) NOT NULL,
    role VARCHAR(50) DEFAULT 'user',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(tenant_id, username),
    UNIQUE(tenant_id, email)
);

CREATE INDEX idx_users_tenant ON users(tenant_id);

-- ============================================================================
-- 2. Ontology Core Tables (P1)
-- ============================================================================

-- 2.1 Value Type: reusable semantic value definitions
CREATE TABLE ontology_value_types (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    display_name VARCHAR(255),
    description TEXT,
    base_type VARCHAR(20) NOT NULL CHECK (base_type IN ('string','int','float','date','boolean','json')),
    validation_regex VARCHAR(500),
    enum_values JSONB,               -- ["option1", "option2"]
    version INTEGER DEFAULT 1,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(tenant_id, name)
);
CREATE INDEX idx_ontology_value_types_tenant ON ontology_value_types(tenant_id);

-- 2.2 Object Type: entity definitions (Palantir Object Type equivalent)
CREATE TABLE ontology_object_types (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,                    -- e.g. "Employee"
    display_name VARCHAR(255),                     -- e.g. "员工"
    description TEXT,
    icon VARCHAR(50) DEFAULT 'box',

    -- Property definitions stored as JSON Schema-like array
    properties JSONB NOT NULL DEFAULT '[]',
    -- [
    --   {"name":"name","type":"string","required":true,"display_name":"姓名"},
    --   {"name":"department","type":"string","link_to":"Department","required":false}
    -- ]

    -- Interface implementations
    implemented_interfaces JSONB NOT NULL DEFAULT '[]',  -- [interface_id_1, interface_id_2]

    -- Neo4j mapping
    neo4j_label VARCHAR(255) NOT NULL,             -- e.g. "Employee"
    neo4j_constraints JSONB DEFAULT '[]',          -- generated by compiler

    status VARCHAR(20) DEFAULT 'draft' CHECK (status IN ('draft','active','archived')),
    version INTEGER DEFAULT 1,
    compiled_at TIMESTAMPTZ,
    compile_status VARCHAR(20) DEFAULT 'pending' CHECK (compile_status IN ('pending','compiled','error')),
    compile_errors JSONB DEFAULT '[]',

    created_by UUID REFERENCES users(id),
    updated_by UUID REFERENCES users(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    UNIQUE(tenant_id, name)
);
CREATE INDEX idx_ontology_object_types_tenant ON ontology_object_types(tenant_id);
CREATE INDEX idx_ontology_object_types_status ON ontology_object_types(status);
CREATE INDEX idx_ontology_object_types_compile ON ontology_object_types(tenant_id, compile_status);

-- 2.3 Link Type: relationship definitions (Palantir Link Type equivalent)
CREATE TABLE ontology_link_types (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,                    -- e.g. "belongs_to"
    display_name VARCHAR(255),
    description TEXT,

    source_object_type_id UUID NOT NULL REFERENCES ontology_object_types(id) ON DELETE CASCADE,
    target_object_type_id UUID NOT NULL REFERENCES ontology_object_types(id) ON DELETE CASCADE,
    cardinality VARCHAR(20) DEFAULT 'MANY_TO_ONE' CHECK (cardinality IN ('ONE_TO_ONE','ONE_TO_MANY','MANY_TO_ONE','MANY_TO_MANY')),

    -- Neo4j mapping
    neo4j_edge_type VARCHAR(255) NOT NULL,         -- e.g. "BELONGS_TO"
    neo4j_properties JSONB DEFAULT '[]',           -- edge property definitions

    status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('draft','active','archived')),
    version INTEGER DEFAULT 1,
    created_by UUID REFERENCES users(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    UNIQUE(tenant_id, name)
);
CREATE INDEX idx_ontology_link_types_tenant ON ontology_link_types(tenant_id);
CREATE INDEX idx_ontology_link_types_source ON ontology_link_types(source_object_type_id);
CREATE INDEX idx_ontology_link_types_target ON ontology_link_types(target_object_type_id);

-- 2.4 Interface Type: semantic contracts (Palantir Interface equivalent)
CREATE TABLE ontology_interfaces (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,                    -- e.g. "Identifiable"
    display_name VARCHAR(255),
    description TEXT,

    -- Contract requirements
    required_properties JSONB NOT NULL DEFAULT '[]',
    -- [{"name":"id","type":"string","required":true}]

    required_links JSONB NOT NULL DEFAULT '[]',
    -- [{"name":"belongs_to","target_type":"Organization"}]

    status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('draft','active','archived')),
    created_by UUID REFERENCES users(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    UNIQUE(tenant_id, name)
);
CREATE INDEX idx_ontology_interfaces_tenant ON ontology_interfaces(tenant_id);

-- 2.5 Action Type: operation definitions (Palantir Action Type equivalent)
CREATE TABLE ontology_action_types (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,                    -- e.g. "AssignManager"
    display_name VARCHAR(255),
    description TEXT,

    target_object_type_id UUID NOT NULL REFERENCES ontology_object_types(id) ON DELETE CASCADE,

    -- Parameter definitions
    parameters JSONB NOT NULL DEFAULT '[]',
    -- [{"name":"manager_id","type":"Employee","required":true,"display_name":"上级经理"}]

    -- What this action modifies
    modifies_properties JSONB NOT NULL DEFAULT '[]',
    modifies_links JSONB NOT NULL DEFAULT '[]',

    -- Rules / Guardrails (OPA Rego or JSON expression)
    rules JSONB NOT NULL DEFAULT '[]',
    -- [{"type":"opa","policy":"package ontology\n..."}]

    -- Execution strategy
    execution_type VARCHAR(20) DEFAULT 'direct' CHECK (execution_type IN ('direct','function_backed','workflow')),
    function_id UUID,                              -- references ontology_functions (if function_backed)
    workflow_id UUID,                              -- references decision_flows (if workflow)

    status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('draft','active','archived')),
    created_by UUID REFERENCES users(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    UNIQUE(tenant_id, name)
);
CREATE INDEX idx_ontology_action_types_tenant ON ontology_action_types(tenant_id);
CREATE INDEX idx_ontology_action_types_target ON ontology_action_types(target_object_type_id);

-- 2.6 Function Definition: custom business logic
CREATE TABLE ontology_functions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    display_name VARCHAR(255),
    description TEXT,

    language VARCHAR(20) DEFAULT 'python' CHECK (language IN ('python','typescript')),
    code TEXT NOT NULL,
    read_only BOOLEAN DEFAULT FALSE,
    timeout_seconds INTEGER DEFAULT 30,
    memory_mb INTEGER DEFAULT 256,

    status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('draft','active','archived')),
    current_version INTEGER DEFAULT 1,
    created_by UUID REFERENCES users(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    UNIQUE(tenant_id, name)
);
CREATE INDEX idx_ontology_functions_tenant ON ontology_functions(tenant_id);

-- 2.7 Function Versions
CREATE TABLE ontology_function_versions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    function_id UUID NOT NULL REFERENCES ontology_functions(id) ON DELETE CASCADE,
    version INTEGER NOT NULL,
    code TEXT NOT NULL,
    change_notes TEXT,
    created_by UUID REFERENCES users(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(function_id, version)
);
CREATE INDEX idx_ontology_function_versions_func ON ontology_function_versions(function_id);

-- ============================================================================
-- 3. Ontology Instance Tables (Writeback)
-- ============================================================================

-- 3.1 Object Instances: actual entity objects written back from Neo4j
CREATE TABLE ontology_objects (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    object_type_id UUID NOT NULL REFERENCES ontology_object_types(id) ON DELETE CASCADE,

    -- Business key (unique within tenant + object_type)
    object_key VARCHAR(255) NOT NULL,

    -- Properties snapshot (JSON)
    properties JSONB NOT NULL DEFAULT '{}',

    -- Neo4j reference
    neo4j_node_id VARCHAR(255),

    -- Source tracking
    source_type VARCHAR(50) DEFAULT 'manual',      -- manual / cdc / etl / action
    source_id VARCHAR(255),                        -- e.g. CDC event ID, ETL job ID

    status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active','archived','deleted')),
    created_by UUID REFERENCES users(id),
    updated_by UUID REFERENCES users(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    UNIQUE(tenant_id, object_type_id, object_key)
);
CREATE INDEX idx_ontology_objects_tenant ON ontology_objects(tenant_id);
CREATE INDEX idx_ontology_objects_type ON ontology_objects(object_type_id);
CREATE INDEX idx_ontology_objects_key ON ontology_objects(tenant_id, object_type_id, object_key);
CREATE INDEX idx_ontology_objects_neo4j ON ontology_objects(neo4j_node_id);
CREATE INDEX idx_ontology_objects_properties ON ontology_objects USING GIN (properties);

-- 3.2 Link Instances: actual relationships written back from Neo4j
CREATE TABLE ontology_links (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    link_type_id UUID NOT NULL REFERENCES ontology_link_types(id) ON DELETE CASCADE,

    source_object_id UUID NOT NULL REFERENCES ontology_objects(id) ON DELETE CASCADE,
    target_object_id UUID NOT NULL REFERENCES ontology_objects(id) ON DELETE CASCADE,

    -- Properties snapshot (for edge attributes)
    properties JSONB NOT NULL DEFAULT '{}',

    neo4j_rel_id VARCHAR(255),

    source_type VARCHAR(50) DEFAULT 'manual',
    source_id VARCHAR(255),

    created_by UUID REFERENCES users(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_ontology_links_tenant ON ontology_links(tenant_id);
CREATE INDEX idx_ontology_links_type ON ontology_links(link_type_id);
CREATE INDEX idx_ontology_links_source ON ontology_links(source_object_id);
CREATE INDEX idx_ontology_links_target ON ontology_links(target_object_id);
CREATE INDEX idx_ontology_links_properties ON ontology_links USING GIN (properties);

-- ============================================================================
-- 4. Action Execution & Audit (Writeback + Audit)
-- ============================================================================

CREATE TABLE action_execution_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    action_type_id UUID NOT NULL REFERENCES ontology_action_types(id) ON DELETE SET NULL,

    target_object_id UUID REFERENCES ontology_objects(id) ON DELETE SET NULL,
    target_object_type_id UUID REFERENCES ontology_object_types(id) ON DELETE SET NULL,

    -- Execution context
    parameters JSONB NOT NULL DEFAULT '{}',
    result JSONB,
    status VARCHAR(20) NOT NULL CHECK (status IN ('pending','running','success','failed','timeout')),
    error_message TEXT,

    -- Rules evaluation snapshot
    rules_evaluation JSONB DEFAULT '[]',

    -- Execution metadata
    execution_type VARCHAR(20),                    -- actual executed type
    function_version INTEGER,                      -- if function_backed
    workflow_execution_id UUID,                    -- if workflow

    -- Performance
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    duration_ms INTEGER,

    -- Audit
    executed_by UUID NOT NULL REFERENCES users(id),
    executed_at TIMESTAMPTZ DEFAULT NOW(),
    ip_address INET,
    user_agent TEXT
);
CREATE INDEX idx_action_logs_tenant ON action_execution_logs(tenant_id);
CREATE INDEX idx_action_logs_action ON action_execution_logs(action_type_id);
CREATE INDEX idx_action_logs_object ON action_execution_logs(target_object_id);
CREATE INDEX idx_action_logs_status ON action_execution_logs(status);
CREATE INDEX idx_action_logs_executed_at ON action_execution_logs(tenant_id, executed_at);

-- ============================================================================
-- 5. Compile Logs
-- ============================================================================

CREATE TABLE ontology_compile_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    compile_type VARCHAR(20) NOT NULL CHECK (compile_type IN ('full','incremental')),
    target_object_type_id UUID REFERENCES ontology_object_types(id) ON DELETE SET NULL,

    status VARCHAR(20) NOT NULL CHECK (status IN ('running','success','failed')),
    errors JSONB DEFAULT '[]',
    warnings JSONB DEFAULT '[]',
    graphql_schema_snapshot TEXT,
    neo4j_constraints_snapshot JSONB DEFAULT '[]',

    started_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    duration_ms INTEGER,

    executed_by UUID REFERENCES users(id)
);
CREATE INDEX idx_compile_logs_tenant ON ontology_compile_logs(tenant_id);
CREATE INDEX idx_compile_logs_status ON ontology_compile_logs(status);

-- ============================================================================
-- 6. AIP Layer Tables
-- ============================================================================

-- 6.1 LLM Call Logs
CREATE TABLE aip_llm_calls (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    user_id UUID REFERENCES users(id),

    -- Request
    provider VARCHAR(50) NOT NULL,                 -- openai / azure / claude / ollama
    model VARCHAR(100) NOT NULL,
    messages JSONB NOT NULL,
    parameters JSONB DEFAULT '{}',                 -- temperature, max_tokens, etc.

    -- Response
    response_text TEXT,
    response_json JSONB,
    finish_reason VARCHAR(50),

    -- Token usage
    prompt_tokens INTEGER DEFAULT 0,
    completion_tokens INTEGER DEFAULT 0,
    total_tokens INTEGER DEFAULT 0,

    -- Cost (in tenant's currency, e.g. USD cents)
    estimated_cost_cents INTEGER DEFAULT 0,

    -- Performance
    first_token_ms INTEGER,
    total_duration_ms INTEGER,

    -- Metadata
    session_id VARCHAR(255),
    trace_id VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_aip_llm_calls_tenant ON aip_llm_calls(tenant_id);
CREATE INDEX idx_aip_llm_calls_user ON aip_llm_calls(user_id);
CREATE INDEX idx_aip_llm_calls_session ON aip_llm_calls(session_id);
CREATE INDEX idx_aip_llm_calls_created ON aip_llm_calls(tenant_id, created_at);

-- 6.2 Agent Sessions
CREATE TABLE aip_agent_sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    user_id UUID REFERENCES users(id),

    agent_id VARCHAR(255) NOT NULL,
    agent_name VARCHAR(255),

    -- Session state (LangGraph checkpoint compatible)
    state JSONB DEFAULT '{}',
    thread_id VARCHAR(255),

    status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active','paused','completed','error')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    ended_at TIMESTAMPTZ
);
CREATE INDEX idx_aip_agent_sessions_tenant ON aip_agent_sessions(tenant_id);
CREATE INDEX idx_aip_agent_sessions_thread ON aip_agent_sessions(thread_id);

-- 6.3 RAG Query Logs
CREATE TABLE aip_rag_queries (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    user_id UUID REFERENCES users(id),

    query_text TEXT NOT NULL,
    entity_context JSONB DEFAULT '{}',             -- extracted ontology entities

    -- Retrieval stats
    vector_results_count INTEGER DEFAULT 0,
    graph_results_count INTEGER DEFAULT 0,
    reranked_results_count INTEGER DEFAULT 0,

    -- Final answer
    answer_text TEXT,
    sources JSONB DEFAULT '[]',                    -- [{"source":"vector","id":"...","score":0.95}]

    -- Performance
    vector_search_ms INTEGER,
    graph_search_ms INTEGER,
    rerank_ms INTEGER,
    llm_generation_ms INTEGER,
    total_duration_ms INTEGER,

    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_aip_rag_queries_tenant ON aip_rag_queries(tenant_id);
CREATE INDEX idx_aip_rag_queries_created ON aip_rag_queries(tenant_id, created_at);

-- 6.4 Guardrails Logs
CREATE TABLE aip_guardrails_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    user_id UUID REFERENCES users(id),

    check_type VARCHAR(50) NOT NULL CHECK (check_type IN ('input','output','pii')),
    llm_call_id UUID REFERENCES aip_llm_calls(id) ON DELETE SET NULL,

    -- Input / Output content snapshot
    content_snapshot TEXT,
    content_hash VARCHAR(64),                      -- SHA-256 for integrity

    -- Check results
    passed BOOLEAN NOT NULL,
    violations JSONB DEFAULT '[]',                 -- [{"rule":"prompt_injection","confidence":0.98}]
    action_taken VARCHAR(50),                      -- blocked / masked / warned / allowed

    -- PII specific
    pii_entities JSONB DEFAULT '[]',               -- [{"type":"email","value":"***","position":[10,20]}]

    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_aip_guardrails_tenant ON aip_guardrails_logs(tenant_id);
CREATE INDEX idx_aip_guardrails_llm ON aip_guardrails_logs(llm_call_id);
CREATE INDEX idx_aip_guardrails_type ON aip_guardrails_logs(tenant_id, check_type);

-- ============================================================================
-- 7. Foundry / Data Integration Tables
-- ============================================================================

-- 7.1 Data Sources
CREATE TABLE data_sources (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    source_type VARCHAR(50) NOT NULL CHECK (source_type IN ('mysql','postgresql','oracle','mongodb','kafka','s3','api')),
    connection_config JSONB NOT NULL,              -- host, port, credentials_ref, etc.
    description TEXT,
    status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active','inactive','error')),
    last_tested_at TIMESTAMPTZ,
    created_by UUID REFERENCES users(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(tenant_id, name)
);
CREATE INDEX idx_data_sources_tenant ON data_sources(tenant_id);

-- 7.2 Data Integration Pipelines
CREATE TABLE data_pipelines (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    description TEXT,

    source_id UUID NOT NULL REFERENCES data_sources(id),
    target_object_type_id UUID REFERENCES ontology_object_types(id),

    -- Pipeline configuration (SeaTunnel config snapshot)
    config_json JSONB NOT NULL,
    config_yaml TEXT,

    schedule_type VARCHAR(20) DEFAULT 'manual' CHECK (schedule_type IN ('manual','cron','event')),
    schedule_expr VARCHAR(255),                    -- cron expression or event trigger

    status VARCHAR(20) DEFAULT 'draft' CHECK (status IN ('draft','active','paused','archived')),
    last_run_at TIMESTAMPTZ,
    last_run_status VARCHAR(20),
    last_run_log TEXT,

    created_by UUID REFERENCES users(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_data_pipelines_tenant ON data_pipelines(tenant_id);
CREATE INDEX idx_data_pipelines_source ON data_pipelines(source_id);

-- 7.3 CDC Subscriptions
CREATE TABLE cdc_subscriptions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    data_source_id UUID NOT NULL REFERENCES data_sources(id) ON DELETE CASCADE,

    connector_name VARCHAR(255) NOT NULL,          -- Debezium connector name
    database_name VARCHAR(255) NOT NULL,
    table_name VARCHAR(255) NOT NULL,

    -- Mapping to Ontology
    target_object_type_id UUID REFERENCES ontology_object_types(id),
    field_mappings JSONB NOT NULL DEFAULT '[]',    -- [{"source":"emp_id","target":"object_key"}]

    status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active','paused','error')),
    lag_seconds INTEGER DEFAULT 0,
    last_event_at TIMESTAMPTZ,
    total_events BIGINT DEFAULT 0,

    created_by UUID REFERENCES users(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_cdc_subscriptions_tenant ON cdc_subscriptions(tenant_id);
CREATE INDEX idx_cdc_subscriptions_source ON cdc_subscriptions(data_source_id);

-- ============================================================================
-- 8. Existing Tables (Preserved from v1.0)
-- ============================================================================

-- Documents (from v1.0, updated with tenant_id)
CREATE TABLE IF NOT EXISTS documents (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    filename VARCHAR(255) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    file_size BIGINT NOT NULL,
    mime_type VARCHAR(100),
    bucket_name VARCHAR(255) DEFAULT 'meatapivot',
    object_key VARCHAR(512) NOT NULL,
    uploaded_by UUID REFERENCES users(id),
    status VARCHAR(50) DEFAULT 'uploaded',
    metadata JSONB DEFAULT '{}',
    embedding_vector_id VARCHAR(255),              -- reference to Milvus
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_documents_tenant ON documents(tenant_id);

-- Decision Flows (from v1.0, updated with tenant_id)
CREATE TABLE IF NOT EXISTS decision_flows (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    dag_definition JSONB NOT NULL,
    version INTEGER DEFAULT 1,
    created_by UUID REFERENCES users(id),
    status VARCHAR(50) DEFAULT 'draft',
    last_run_at TIMESTAMPTZ,
    last_run_status VARCHAR(50),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_decision_flows_tenant ON decision_flows(tenant_id);

-- Flow Executions (from v1.0, updated with tenant_id)
CREATE TABLE IF NOT EXISTS flow_executions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    flow_id UUID NOT NULL REFERENCES decision_flows(id) ON DELETE CASCADE,
    execution_id VARCHAR(255) UNIQUE NOT NULL,
    status VARCHAR(50) DEFAULT 'pending',
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    result JSONB,
    error_message TEXT,
    logs JSONB DEFAULT '[]',
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_flow_executions_tenant ON flow_executions(tenant_id);
CREATE INDEX idx_flow_executions_flow ON flow_executions(flow_id);

-- Knowledge Graph Entities (from v1.0, updated with tenant_id)
CREATE TABLE IF NOT EXISTS kg_entities (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    entity_name VARCHAR(255) NOT NULL,
    entity_type VARCHAR(100),
    properties JSONB DEFAULT '{}',
    neo4j_node_id VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_kg_entities_tenant ON kg_entities(tenant_id);

-- ============================================================================
-- 9. Update Triggers for updated_at
-- ============================================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply to all tables with updated_at
DO $$
DECLARE
    tbl RECORD;
BEGIN
    FOR tbl IN
        SELECT table_name
        FROM information_schema.columns
        WHERE column_name = 'updated_at'
          AND table_schema = 'public'
    LOOP
        EXECUTE format(
            'DROP TRIGGER IF EXISTS trg_%I_updated_at ON %I;',
            tbl.table_name, tbl.table_name
        );
        EXECUTE format(
            'CREATE TRIGGER trg_%I_updated_at
             BEFORE UPDATE ON %I
             FOR EACH ROW
             EXECUTE FUNCTION update_updated_at_column();',
            tbl.table_name, tbl.table_name
        );
    END LOOP;
END $$;

-- ============================================================================
-- 10. Row Level Security (Optional, for high-security tenants)
-- ============================================================================

-- Example: Enable RLS on ontology_objects
-- ALTER TABLE ontology_objects ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY tenant_isolation ON ontology_objects
--     USING (tenant_id = current_setting('app.current_tenant')::UUID);

-- ============================================================================
-- 11. Comments
-- ============================================================================

COMMENT ON TABLE ontology_object_types IS 'Palantir Object Type equivalent: defines entity schemas';
COMMENT ON TABLE ontology_link_types IS 'Palantir Link Type equivalent: defines relationships between objects';
COMMENT ON TABLE ontology_interfaces IS 'Palantir Interface equivalent: semantic contracts that ObjectTypes must implement';
COMMENT ON TABLE ontology_action_types IS 'Palantir Action Type equivalent: operations that modify ontology instances';
COMMENT ON TABLE ontology_functions IS 'Palantir Functions equivalent: custom business logic backed by code';
COMMENT ON TABLE ontology_objects IS 'Writeback table: actual entity instances synchronized from Neo4j';
COMMENT ON TABLE ontology_links IS 'Writeback table: actual relationships synchronized from Neo4j';
COMMENT ON TABLE action_execution_logs IS 'Audit trail for every Action execution with full context';
COMMENT ON TABLE aip_llm_calls IS 'Comprehensive logging for all LLM interactions for cost and compliance tracking';
COMMENT ON TABLE aip_rag_queries IS 'Retrieval-Augmented Generation query history with performance metrics';
