apiVersion: v1
kind: Service
metadata:
  name: {{ include "kdp.fullname" . }}-frontend
  labels:
    {{- include "kdp.frontendLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kdp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
